name: 🚀 Release APK

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Release APK
        working-directory: android-studio
        run: ./gradlew assembleRelease --no-daemon

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release APK
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: android-studio/app/build/outputs/apk/release/app-release.apk
          asset_name: app-${{ github.ref_name }}.apk
          asset_content_type: application/vnd.android.package-archive
